/* import the fontawesome core */
import { library } from '@fortawesome/fontawesome-svg-core'
import { faCalendar } from '@fortawesome/free-regular-svg-icons'
import {  faAddressBook, faArrowRight, faBed,  faBedPulse,  faCalendarAlt, faCalendarCheck, faCapsules, faChevronDown, faChevronRight, faChevronUp, faCircleInfo, faClipboard, faClipboardList, faDownload, faEllipsis, faEnvelope, faEnvelopeCircleCheck, faEnvelopeOpenText, faFileMedical, faFilePen, faFileWaveform, faFilter, faFloppyDisk, faFolderOpen, faHeartPulse, faHistory, faHospitalUser, faIdBadge, faIdCard, faLock, faMagnifyingGlass, faMicroscope, faNotesMedical, faPaperPlane, faPhone, faPrescription, faPrint, faRuler, faShuffle,  faSignInAlt,  faSpinner, faStethoscope,  faTemperatureHigh,  faTrash,faUser,faUserCircle,faUserDoctor,faUserInjured,faUserMd, faUserPlus, faUsers, faUserTag, faVialCircleCheck, faWeight } from '@fortawesome/free-solid-svg-icons'

library.add(
    faMagnifyingGlass,
    faUserPlus,
    faSignInAlt,
    faUsers,
    faUser,
    faEnvelopeCircleCheck,
    faBedPulse,
    faClipboardList,
    faArrowRight,
    faFilter,
    faPhone,
    faAddressBook,
    faUserCircle,
    faBed,
    faCapsules,
    faFileWaveform,
    faNotesMedical,
    faCalendar,
    faTrash,
    faFloppyDisk,
    faShuffle,
    faDownload,
    faPrint,
    faVialCircleCheck,
    faCircleInfo,
    faEnvelope,
    faFolderOpen,
    faStethoscope,
    faTemperatureHigh,
    faRuler,
    faWeight,
    faUserDoctor,
    faCalendarAlt,
    faUserMd,
    faFilePen,
    faClipboard,
    faChevronUp,
    faChevronDown,
    faChevronRight,
    faCalendarCheck,
    faUserInjured,
    faEnvelopeOpenText,
    faPrescription,
    faMicroscope,
    faLock,
    faSpinner,
    faEllipsis,
    faHistory,
    faHospitalUser,
    faFileMedical,
    faClipboard,
    faIdCard,
    faIdBadge,
    faUserTag,
    faPaperPlane,
    faHeartPulse

)
